import { Inter } from 'next/font/google'
import Navigator from '@/components/navbar/Navigator'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <div className="min-w-screen h-fit">
            <Navigator>
                {children}
            </Navigator>
        </div>
    )
}
